// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Ball: typeof import('./src/components/business/BallBox/Ball.vue')['default']
    BallBox: typeof import('./src/components/business/BallBox/index.vue')['default']
    BottomBar: typeof import('./src/components/custom/BottomBar.vue')['default']
    NavBar: typeof import('./src/components/custom/NavBar.vue')['default']
    NumberCard: typeof import('./src/components/business/NumberCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SelectedBall: typeof import('./src/components/business/SelectedBall.vue')['default']
    VanButton: typeof import('vant/es')['Button']
    VanIcon: typeof import('vant/es')['Icon']
    VanImage: typeof import('vant/es')['Image']
    VanNavBar: typeof import('vant/es')['NavBar']
    VanStepper: typeof import('vant/es')['Stepper']
    VanSwipe: typeof import('vant/es')['Swipe']
    VanSwipeItem: typeof import('vant/es')['SwipeItem']
    VerticalAdaptiveBox: typeof import('./src/components/common/VerticalAdaptiveBox.vue')['default']
  }
}
